<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\externals\ICSharpCode.TextEditor\Project\ICSharpCode.TextEditor.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\GitExtUtils\GitExtUtils.csproj" />
    <ProjectReference Include="..\..\..\CommonTestUtils\CommonTestUtils.csproj" />
  </ItemGroup>

</Project>
