<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <!-- Disable C#13+ keyword "field" -->
    <LangVersion>13</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Drawing.EnableUnixSupport" Value="true" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit.Extension.Net90PluggableAgent" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\app\GitCommands\GitCommands.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\GitExtUtils\GitExtUtils.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\GitUI\GitUI.csproj" />
    <ProjectReference Include="..\..\..\..\src\plugins\GitUIPluginInterfaces\GitUIPluginInterfaces.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\ResourceManager\ResourceManager.csproj" />
    <ProjectReference Include="..\..\..\CommonTestUtils\CommonTestUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Editor\Diff\*.diff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
