<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory)\.., Directory.Build.props))\Directory.Build.props" />

  <PropertyGroup>
    <RootNamespace>$([System.String]::Copy('$(MSBuildProjectName)').Replace('.Tests', 'Tests'))</RootNamespace>
    
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <!--
      Direct unit test artifacts to be placed under tests/UnitTests folder
    -->
  <PropertyGroup>
    <BaseOutputPath>$([MSBuild]::NormalizeDirectory('$(ArtifactsUnitTestsDir)', '$(OutDirName)'))</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)</OutputPath>
  </PropertyGroup>
	<!--
    ============================================================
                      GenerateImplicitNamespaceImports
    Generates implicit namespace imports source to intermediate directory for Windows Forms projects
    ============================================================
    -->
	<ItemGroup Condition="('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable')">
		<!--
      SDK defines the following global usings:
      * System
      * System.Collections.Generic
      * System.Linq
      * System.Threading.Tasks
    -->
		<Using Include="System.Drawing" />
		<!--<Using Include="System.Windows.Forms" />-->
	</ItemGroup>
</Project>
